CREATE TABLE AIRCRAFT (
    ID CHAR(36) NOT NULL,
    DESIGNATION VARCHAR(25) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    NICKNAME VARCHAR(50),
    MANUFACTURER VARCHAR(50),
    PRODUCED INTEGER,
    FIRST_FLIGHT DATE,
    PRIMARY KEY (ID),
    UNIQUE (DESIGNATION)
);
